{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.programs.powershell;
in {
  options.programs.powershell = {
    enable = mkEnableOption "PowerShell";
    profile = mkOption {
      type = with types; nullOr (either path lines);
      description = ''
        PowerShell profile written to {file}`~/.config/powershell/Microsoft.PowerShell_profile.ps1`
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages = [pkgs.powershell];

    home.file.".config/powershell/Microsoft.PowerShell_profile.ps1" = let
      configHeader = ''
        # PowerShell profile
        #
        # Generated by Home Manager, do not edit manually.
      '';
    in
      mkIf (cfg.profile != null) {
        source =
          if builtins.isPath cfg.profile
          then cfg.profile
          else
            pkgs.writeText "powershell/profile.ps1" ''
              ${configHeader}
              ${cfg.profile}
            '';
      };
  };
}
