-- local indent_size = require("utils").indent_size(2)
-- local text_width = require("utils").text_width(120)
--
-- vim.opt_local.shiftwidth = indent_size
-- vim.opt_local.tabstop = indent_size
-- vim.bo.textwidth = text_width
