search_mode = "fuzzy"
search_mode_shell_up_key_binding = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "global"
workspaces = true

style = "auto"
inline_height = 40
invert = true
history_format = "{time}\t{command}\t{duration}"
show_preview = false
max_preview_height = 4
show_help = true

exit_mode = "return-original"

enter_accept = false
word_jump_mode = "emacs"

history_filter = ["^pass"]
cwd_filter = [".*password-store.*"]

[stats]

ignored_commands = [
  "ls",
  "vi",
  "cd",
  # Interactive menus
  "v",
  "z",
  "zi",
  "ji",
]

[dotfiles]

enabled = true
